// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDzxG_oaHons3PvD49_a2rhwtrnpy_KcL8',
    appId: '1:918199999751:web:b4819d739510f4762df9a2',
    messagingSenderId: '918199999751',
    projectId: 'movies-app-1b8c6',
    authDomain: 'movies-app-1b8c6.firebaseapp.com',
    storageBucket: 'movies-app-1b8c6.firebasestorage.app',
    measurementId: 'G-FNEY3Q7DD3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCHlVouvUHDPIF5xYd8VXfx566QC6-Fr1Q',
    appId: '1:918199999751:android:832b40998d1c21ec2df9a2',
    messagingSenderId: '918199999751',
    projectId: 'movies-app-1b8c6',
    storageBucket: 'movies-app-1b8c6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBE8M13bmmhyE3IomUU0j62GUe7mA4UBsY',
    appId: '1:918199999751:ios:1981f7e748416a892df9a2',
    messagingSenderId: '918199999751',
    projectId: 'movies-app-1b8c6',
    storageBucket: 'movies-app-1b8c6.firebasestorage.app',
    iosBundleId: 'com.example.moviesApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBE8M13bmmhyE3IomUU0j62GUe7mA4UBsY',
    appId: '1:918199999751:ios:1981f7e748416a892df9a2',
    messagingSenderId: '918199999751',
    projectId: 'movies-app-1b8c6',
    storageBucket: 'movies-app-1b8c6.firebasestorage.app',
    iosBundleId: 'com.example.moviesApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDzxG_oaHons3PvD49_a2rhwtrnpy_KcL8',
    appId: '1:918199999751:web:4858186e2535a66d2df9a2',
    messagingSenderId: '918199999751',
    projectId: 'movies-app-1b8c6',
    authDomain: 'movies-app-1b8c6.firebaseapp.com',
    storageBucket: 'movies-app-1b8c6.firebasestorage.app',
    measurementId: 'G-47QP4SNX8N',
  );
}
